language: swift
osx_image: xcode8.2
xcode_workspace: Cargo.xcworkspace
xcode_scheme: Cargo

before_install:
  - pod update
  - gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  - rvm get stable
  - gem install xcpretty

script:
  - set -o pipefail && xcodebuild test 'ONLY_ACTIVE_ARCH=NO' 'ARCHS=arm64 armv7 armv7s i386 x86_64' 'GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES' 'GCC_GENERATE_TEST_COVERAGE_FILES=YES' -workspace Cargo.xcworkspace -scheme CargoTest -enableCodeCoverage YES -destination { platform:iOS Simulator, id:A538AE42-68FC-4C17-B955-41D4660F6001, OS:9.3, name:iPhone 5 } | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash) -X xcodeplist